services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: rag_ollama
    restart: always
    dns:
      - 8.8.8.8
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  fastapi:
    build: .
    container_name: rag_api
    restart: always
    depends_on:
      - postgres
      - ollama
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ragdb
      OLLAMA_BASE_URL: http://ollama:11434
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
  ollama: